server:
  port: 8080
spring:
  application:
    name: supermarket-list
    admin:
      jmx-name: supermarket-list
  profiles:
    active: dev, database
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  jackson:
    default-property-inclusion: NON_EMPTY
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
jwt:
  secret: qwe123
---
spring:
  config:
    activate:
      on-profile:
        - dev
  datasource:
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
---
spring:
  config:
    activate:
      on-profile:
        - database
  jpa:
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  flyway:
    locations:
      - classpath:/db/migration/common
      - classpath:/db/migration/database
---
spring:
  config:
    activate:
      on-profile:
        - in-memory
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: test
    password: test
  h2:
    console:
      enabled: true
  flyway:
    locations:
      - classpath:/db/migration/common
      - classpath:/db/migration/inmemory
---
spring:
  config:
    activate:
      on-profile:
        - production
  jpa:
    show-sql: false
    datasource:
      url: jdbc:postgres://uigvgqvxrnzhky:c1210a73e956e75bafee21aee8a59b5446a259d0328f48cce52be1d6b316a42d@ec2-54-204-28-187.compute-1.amazonaws.com:5432/d5i6613aev8e96
      username: uigvgqvxrnzhky
      password: c1210a73e956e75bafee21aee8a59b5446a259d0328f48cce52be1d6b316a42d
logging:
  level:
    root: error
jwt:
  secret: "!^fA;dH_st29``KL"